# Generated by Django 4.0.3 on 2022-03-27 12:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0003_category_newsmodel_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsmodel',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='news_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
