# Generated by Django 4.0.3 on 2022-03-27 13:11

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_newsmodel_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsmodel',
            name='body',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
