# Generated by Django 4.0.3 on 2022-05-02 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_alter_newsmodel_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsmodel',
            name='pinned',
            field=models.BooleanField(default=False),
        ),
    ]
