# Generated by Django 4.0.3 on 2022-05-06 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.CharField(default='/static/images/avatar4.png', max_length=200),
        ),
    ]
