# Generated by Django 4.0.3 on 2022-04-22 05:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province', models.CharField(blank=True, max_length=100, null=True)),
                ('district', models.CharField(blank=True, max_length=100, null=True)),
                ('local', models.CharField(blank=True, max_length=100, null=True)),
                ('employee_nature', models.CharField(max_length=100, verbose_name='Nature of Employee')),
                ('fiscal_year', models.CharField(max_length=100, verbose_name='year')),
                ('monthly_salary', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monthly Salary')),
                ('employeee_provident_fund', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Employee Provident Fund')),
                ('months', models.IntegerField(verbose_name='Months')),
                ('citizen_investment_trust', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Citizen Investment Trust')),
                ('bonus', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Bonus')),
                ('insurance', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Insurance')),
                ('final_tax', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Final Tax')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
