# Generated by Django 4.0.3 on 2022-04-22 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tax', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taxreceipt',
            options={'ordering': ['-id']},
        ),
    ]
